# This is a basic workflow to help you get started with Actions

name: Distribution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
        
  # This workflow contains a single job called "build"
  build-on-macOS:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: "[command] npm install && npm run make"
        run: npm install && npm run make
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: "translator-electron" # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./out/make/zip/darwin/x64/*.zip
        
  # This workflow contains a single job called "build"
  build-on-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: "[command] npm install && npm run make"
        run: npm install && npm run make
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: "translator-electron" # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: .\out\make\squirrel.windows\x64\*.exe
  
      
